### ISSUE TITLE
Adjusting batch size

### ISSUE THREAD

**Issue by miraclesheephaha** [TRI-ML/PF-Track#30]
RuntimeError: CUDA out of memory occurred when I trained f3_q500_1600x640.py.
For this reason, I want to change the batch size to reduce the memory, but I can't find the place to change the batch size. I would like to ask where I can change it.
Or are there other ways to reduce the memory? 
Looking forward to your answer,thank you.

**Comment by ziqipang** [comment]
@miraclesheephaha Thanks for your question! I think the batch size right now is already 1 sample per GPU, so you could have little gains from here. As for reducing the memory, I am not sure how much it will save, but using `FlashAttention` might be useful. In additional, you could also (1) pre-save the image features, since they are not trained for this 3-frame 1600x640 setting; (2) instead of using the regular AdamW optimizer, use 8-bit AdamW (https://huggingface.co/docs/bitsandbytes/main/en/optimizers)

**Comment by miraclesheephaha** [comment]
I finally solved this problem by changing train_backbone in detr3d f3_q500_1600x640.py to False, but before that I only knew that changing batch_size might solve this problem. After reading your answer, I realized that there are other ways. Thank you for your answer!
Another question is that I am curious why train_backbone=True can run when I train detr3d f1_q500_1600x640, but not when training f3_q500_1600x640.
(I use a rtx3080 gpu 10g ram)

**Comment by ziqipang** [comment]
@miraclesheephaha Thanks for the follow up! When using f3, the network will forward on three images then backward, contrasting f1's forwarding on one image then backward. So f3 intuitively costs more GPU memory. That's why I first pretrain the backbone with f1, then freeze it with f3 (https://github.com/TRI-ML/PF-Track/blob/b25410da8dc93ecf84157424f8f28b71dda8966f/projects/configs/tracking/detr3d/f3_q500_1600x640.py#L147). Just as a note, I think my code set the f3_1600x640 settings with `train_backbone=False`, e.g., the link above. Perhaps you change it some time without noticing it.

**Comment by miraclesheephaha** [comment]
Thank you for your guidance, which helped me better understand its operation.
My file name was wrongly written as f3_q500_800x320.py.
If there are any questions in the future, I will raise them.
